matrix:
  include:
    - language: node_js
      before_install:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update
        - sudo apt-get install -y gcc-5 g++-5
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
      node_js:
        - "10"
        - "12"
        - "14"
      install:
        - npm install
        - npm run build
    - language: python
      python: 3.6
      before_install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update
        - sudo apt-get install -y gcc-5 g++-5
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
      install:
        - BUILD_TEST=1 pip install .
      script:
        - python test/python/VrpcCallerTest.py

notifications:
  email:
    - burkhard.heisen@heisenware.com
