name: CI
on: [push, workflow_dispatch]
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm install
      - run: npm run build:addon
      - run: npm run test
